CREATE TABLE IF NOT EXISTS notifications (
    notificationId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
    sourceId INTEGER NOT NULL,  
    receiverId INTEGER NOT NULL,  
    type TEXT NOT NULL,
    seen BOOLEAN NOT NULL DEFAULT FALSE,
    clickedOn BOOLEAN NOT NULL DEFAULT FALSE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (receiverId) REFERENCES users (userId) ON DELETE CASCADE
);