CREATE TABLE IF NOT EXISTS sessions (
	sessionId INTEGER PRIMARY KEY AUTOINCREMENT, 
	sessionKey TEXT NOT NULL, 
	userId INTEGER NOT NULL, 
	FOREIGN KEY (userId) REFERENCES users (userId) ON DELETE CASCADE
);